import {
  autoreplaceGrammar,
  autoreplaceLocal,
  hotJustifHarmf,
  hotJustifInstruction,
  hotJustifLength,
  hotJustifTone,
  hotJustifTruth,
} from "./hotPaste";

export const defaultDimSets = {
  set1: [
    {
      id: "Instructions",
      isCrit: true,
      a: "Instructions_A",
      b: "Instructions_B",
      name: "Instruction following",
      short: "IF",
      better: "is better at following instructions",
    },
    {
      id: "Factuality",
      isCrit: true,
      a: "Factuality_A",
      b: "Factuality_B",
      name: "Factuality",
      short: "F",
      better: "is more accurate",
    },
    {
      id: "Language",
      isCrit: true,
      a: "Language_A",
      b: "Language_B",
      name: "Language fluency",
      short: "LF",
      better: "is better in fluency",
    },
    {
      id: "Coherence",
      isCrit: false,
      a: "Coherence_A",
      b: "Coherence_B",
      name: "Coherence",
      short: "C",
      better: "is more coherent",
    },
    {
      id: "Presentation",
      isCrit: false,
      a: "Presentation_A",
      b: "Presentation_B",
      name: "Presentation",
      short: "P",
      better: "has better presentation",
    },
    {
      id: "Tone",
      isCrit: false,
      a: "Tone_A",
      b: "Tone_B",
      name: "Tone",
      short: "T",
      better: "has a more appropriate tone",
    },
  ],
  set2: [
    {
      id: "Localization",
      isCrit: true,
      a: "Localization_A",
      b: "Localization_B",
      name: "Localization fluency",
      short: "LC",
      better: "is better in localization",
      worth: "is less localized",
      justif: [...autoreplaceLocal, ...autoreplaceGrammar],
      isLang: true,
    },
    {
      id: "Instructions",
      isCrit: true,
      a: "Instructions_A",
      b: "Instructions_B",
      name: "Instruction following",
      short: "IF",
      better: "is better at following instructions",
      worth: "follows instructions worse",
      justif: hotJustifInstruction,
    },
    {
      id: "Truthfulness",
      isCrit: true,
      a: "Truthfulness_A",
      b: "Truthfulness_B",
      name: "Truthfulness",
      short: "TR",
      better: "is more accurate",
      worth: "is less accurate",
      justif: hotJustifTruth,
    },

    {
      id: "Length",
      isCrit: false,
      a: "Length_A",
      b: "Length_B",
      name: "Response Length",
      short: "RL",
      better: `is more dainty/short/long/ has long pleasantries that shift focus away from the answer`,
      worth: `is less dainty/short/long/ has long pleasantries that shift focus away from the answer`,
      justif: hotJustifLength,
    },
    {
      id: "Structure_WritingStyle_Tone",
      isCrit: false,
      a: "Structure_WritingStyle_Tone_A",
      b: "Structure_WritingStyle_Tone_B",
      name: "Structure, Writing Style & Tone",
      short: "SWT",
      better: `is more organized/uses a more appropriate tone/ideas are better presented/text is better read because of successful formatting`,
      worth: `is less organized/uses a less appropriate tone/ideas are worth presented/the text is less readable due to poor formatting.`,
      justif: hotJustifTone,
    },
    {
      id: "Harmless",
      isCrit: true,
      a: "Harmless_A",
      b: "Harmless_B",
      name: "Harmless",
      short: "H",
      better: "has no safety issue",
      worth: "has safety issue",
      justif: hotJustifHarmf,
    },
  ],
};
export const defaultDimTempl = {
  Rate: "",
  Prompt: "",
  Justif: "",
  id: "",
  name: "",
  RateA: "",
  RateB: "",
  ResponseA: "",
  ResponseB: "",
  likert: -1,
  review: "",
};
export const defaultDim = {
  Instructions_A: "",
  Factuality_A: "",
  Coherence_A: "",
  Language_A: "",
  Presentation_A: "",
  Tone_A: "",
  Instructions_B: "",
  Language_B: "",
  Factuality_B: "",
  Coherence_B: "",
  Presentation_B: "",
  Tone_B: "",
  Rate: "",
  Justif: "",
  id: "",
  name: "",
  likert: 0,
  Evals: {
    Instructions_A: 0,
    Factuality_A: 0,
    Coherence_A: 0,
    Language_A: 0,
    Presentation_A: 0,
    Tone_A: 0,
    Instructions_B: 0,
    Language_B: 0,
    Factuality_B: 0,
    Coherence_B: 0,
    Presentation_B: 0,
    Tone_B: 0,
    Rate: 0,
  },
  review: "",
};
export const defaultDmg = {
  Instructions_A: "",
  Factuality_A: "",
  Coherence_A: "",
  Language_A: "",
  Presentation_A: "",
  Tone_A: "",
  Instructions_B: "",
  Language_B: "",
  Factuality_B: "",
  Coherence_B: "",
  Presentation_B: "",
  Tone_B: "",
  Rate: "",
  Justif: "",
  likert: 0,
  id: "",
  name: "",
  Evals: {
    Instructions_A: 0,
    Factuality_A: 0,
    Coherence_A: 0,
    Language_A: 0,
    Presentation_A: 0,
    Tone_A: 0,
    Instructions_B: 0,
    Language_B: 0,
    Factuality_B: 0,
    Coherence_B: 0,
    Presentation_B: 0,
    Tone_B: 0,
    Rate: 0,
  },
  review: "",
};
