export const replacementsEnding = [
  [["resa", "res1", "respa", "куыф", "отв1", "респ1"], "Response A"],
  [["ress", "рсаа"], "responses"],
  [["rr", "рр", "кк"], "response"],
  [["екуы", "tres"], "the response"],
  [["bres"], "Both responses"],
  [["addd"], "Additionally, "],
  [["fexx"], "For example,"],
  [["ilf"], "The response has a problem with language fluency"],
  [["ipu"], "The response has a problem with punctuation"],
  [["lf"], "language fluency"],
  [["ozw"], "Otherwise,"],
  [["o5", "о5", "h5", "щ5"], "Otherwise, BotModel is fully consistent with the user's prompt. There are no issues."],
  [["numl"], "The response uses a numbered list unnecessarily."],
  [["куыи", "res2", "отв2", "resb", "респ2"], "Response B"],
  [["tres", "куыз", "отвв"], "the response"],
  [["isss"], "issue"],
  [["mji", "ьош"], "major issue"],
  [["mni", "ьnш"], "major issue"],
  [["--"], "—"],
  [["##"], `“”`],
  [["tns"], `turn1\nturn2\nturn3\nturn4\n`],
  [["trn"], `turn`],
  [["dim", "вшь"], `Instruction Following\nLanguage fluency\nCoherence\nFactuality\nPresentation\nTone\n`],
  [["exx", "прр"], "for example, "],
  [["кк", "йй", "qq"], "«»"],
  [["refr"], `It is better to rephrase some fragments in the response since it sounds unnatural (" ").`],
  [["@@"], `""`],
];
//hot list

//autorepl
export const autoreplaceNum = [
  {
    oldT: ["num1"],
    newT: `BotModelauses a numbered list unnecessarily`,
    caseSensitive: false,
    show: true,
    title: "1",
  },
  {
    oldT: ["numb1"],
    newT: `BotModelauses a numbered list instead of a bulleted list`,
    caseSensitive: false,
    show: true,
    title: "1->b",
  },
  {
    oldT: ["num2"],
    newT: `BotModelb uses a numbered list unnecessarily`,
    caseSensitive: false,
    show: true,
    title: "2",
  },
  {
    oldT: ["numb2"],
    newT: `BotModelb uses a numbered list instead of a bulleted list`,
    caseSensitive: false,
    show: true,
    title: "2->b",
  },
  {
    oldT: ["num0"],
    newT: `BotModels use a numbered list unnecessarily`,
    caseSensitive: false,
    show: true,
    title: "both",
  },
  {
    oldT: ["numb0"],
    newT: `BotModels use a numbered list instead of a bulleted list`,
    caseSensitive: false,
    show: true,
    title: "both->b",
  },
];

export const autoReplaceToModels = [
  {
    oldT: [
      "@response a",
      "@1",
      "р1",
      "response один",
      "r1",
      "в1",
      "и1",
      "о1",
      "р1",
      "a1",
      "ответ1",
      "Ответ а",
      "Ответ a",
      "ответ 1",
      "ответ один",
      "ответа один",
      "ответа 1",
      "первый ответ",
      "answer 1",
      "answer1",
      "answer A",
      "answerA",
      "@response 1",
      "@response 1",
      "@response one",
      "response a",
      "response 1",
      "response one",
      "interation a",
      "interation 1",
      "interation one",
      "intention a",
      "intention 1",
      "intention one",
      "interaction a",
      "interaction 1",
      "interaction one",
    ],
    newT: "BotModela",
    caseSensitive: false,
  },
  {
    oldT: [
      "response два",
      "в2",
      "a2",
      "@2",
      "р2",
      "r2",
      "р2",
      "о2",
      "р2",
      "Ответ b",
      "Ответ б",
      "answer 2",
      "answer2",
      "answer B",
      "answerB",
      "ответ2",
      "ответ 2",
      "ответ два",
      "ответа два",
      "ответа 2",
      "второй ответ",
      "@response b",
      "@response 2",
      "@response2",
      "@response two",
      "response b",
      "response 2",
      "response two",
      "interation b",
      "interation 1",
      "interation two",
      "intention b",
      "intention 2",
      "intention two",
      "interaction b",
      "interaction 2",
      "interaction two",
    ],
    newT: "BotModelb",
    caseSensitive: false,
  },
  {
    oldT: ["Responses"],
    newT: "BotModels",
    caseSensitive: true,
  },
  {
    oldT: ["в0", "i0", "a0", "interactions"],
    newT: "BotModels",
    caseSensitive: false,
  },
];

const autoReplaceModels = [
  {
    oldT: ["22"],
    newT: `both BotModels`,
    caseSensitive: false,
    show: true,
  },
  {
    oldT: ["m1 ", "м1 "],
    newT: "the model in BotModela",
    caseSensitive: false,
  },
  {
    oldT: ["m2 ", "м2 "],
    newT: "the model in BotModelb",
    caseSensitive: false,
    show: true,
  },
];
const autoReplaceWords = [
  {
    oldT: ["согласна"],
    newT: "согласно",
    caseSensitive: false,
  },
  {
    oldT: ["russian"],
    newT: "Russian",
    caseSensitive: true,
  },
  {
    oldT: ["promo"],
    newT: "prompt",
    caseSensitive: true,
  },
  {
    oldT: ["Promo"],
    newT: "Prompt",
    caseSensitive: true,
  },
  {
    oldT: ["спам", "спан"],
    newT: "span",
    caseSensitive: false,
  },

  {
    oldT: ["википедия"],
    newT: "Википедия",
    caseSensitive: true,
  },
  {
    oldT: ["википедии"],
    newT: "Википедии",
    caseSensitive: true,
  },
  {
    oldT: ["respondent"],
    newT: "response ",
    caseSensitive: false,
  },
];
export const replacementsGeneral = [
  ...autoReplaceToModels,
  ...autoreplaceNum,
  ...autoReplaceModels,
  ...autoReplaceWords,
  ...autoReplaceToModels,
];
//replacement for special responses names type
export const replacementsInteractions = [
  { oldT: ["BotModela"], newT: "Interaction A", caseSensitive: false },
  { oldT: ["BotModelb"], newT: "Interaction B", caseSensitive: false },
  { oldT: ["the answer"], newT: "response", caseSensitive: false },
  { oldT: ["Responses"], newT: "Interactions", caseSensitive: true },
  { oldT: ["Botmodel"], newT: "Interaction", caseSensitive: true },
  {
    oldT: ["answers"],
    newT: "responses",
    caseSensitive: true,
  },
  {
    oldT: ["Answers"],
    newT: "Responses",
    caseSensitive: true,
  },
];
export const replacementsResponses = [
  { oldT: ["BotModela"], newT: "Response A", caseSensitive: false },
  { oldT: ["BotModelb"], newT: "Response B", caseSensitive: false },
  { oldT: ["BotModel, botmodel"], newT: "The Response", caseSensitive: false },
  {
    oldT: ["the answer", "Botmodel"],
    newT: "the response",
    caseSensitive: false,
  },
  {
    oldT: ["answers"],
    newT: "responses",
    caseSensitive: true,
  },
  {
    oldT: ["Answers"],
    newT: "Responses",
    caseSensitive: true,
  },
];
export const replacementsResponsesNum = [
  { oldT: ["BotModela"], newT: "@Response 1", caseSensitive: false },
  { oldT: ["BotModelb"], newT: "@Response 2", caseSensitive: false },
  { oldT: ["BotModels"], newT: "Responses", caseSensitive: false },
  { oldT: ["BotModel"], newT: "the response", caseSensitive: false },
  {
    oldT: ["the answer", "Botmodel"],
    newT: "the response",
    caseSensitive: false,
  },
  {
    oldT: ["answers"],
    newT: "responses",
    caseSensitive: true,
  },
  {
    oldT: ["Answers"],
    newT: "Responses",
    caseSensitive: true,
  },
  {
    oldT: ["@@"],
    newT: "@",
    caseSensitive: false,
  },
];
export const replacementsResponsesNumShort = [
  { oldT: ["BotModela"], newT: "@R1", caseSensitive: false },
  { oldT: ["BotModelb"], newT: "@R2", caseSensitive: false },
  { oldT: ["BotModels"], newT: "Responses", caseSensitive: false },
  { oldT: ["BotModel"], newT: "the response", caseSensitive: false },
  {
    oldT: ["the answer", "Botmodel"],
    newT: "the response",
    caseSensitive: false,
  },
  {
    oldT: ["answers"],
    newT: "responses",
    caseSensitive: true,
  },
  {
    oldT: ["Answers"],
    newT: "Responses",
    caseSensitive: true,
  },
  {
    oldT: ["@@"],
    newT: "@",
    caseSensitive: false,
  },
];
export const replacementsResponsesNum2 = [
  { oldT: ["BotModela"], newT: "Response 1", caseSensitive: false },
  { oldT: ["BotModelb"], newT: "Response 2", caseSensitive: false },
  { oldT: ["BotModels"], newT: "Responses", caseSensitive: false },
  { oldT: ["BotModel"], newT: "The response", caseSensitive: false },
  {
    oldT: ["the answer", "Botmodel"],
    newT: "the response",
    caseSensitive: false,
  },
  {
    oldT: ["answers"],
    newT: "responses",
    caseSensitive: true,
  },
  {
    oldT: ["Answers"],
    newT: "Responses",
    caseSensitive: true,
  },
];
export const replacementsPunctuation = [
  {
    oldT: [" запятая"],
    newT: `,`,
    caseSensitive: false,
    show: true,
  },
  {
    oldT: [" к1", " k1"],
    newT: `"`,
    caseSensitive: false,
    show: true,
  },
  {
    oldT: [" к2", " k2"],
    newT: `"`,
    caseSensitive: false,
    show: true,
  },
  {
    oldT: [" точка"],
    newT: `.`,
    caseSensitive: false,
    show: true,
  },
  {
    oldT: [" кавычка"],
    newT: `"`,
    caseSensitive: false,
    show: true,
  },
];
