export const textParts = [
  { en: ",", ru: "" },
  { en: ".", ru: "" },
  { en: `" "`, ru: "" },
  { en: "it", ru: "" },
  { en: "is", ru: "" },
  { en: "but", ru: "" },
  { en: "and", ru: "" },
  { en: "or", ru: "" },
  { en: "because", ru: "" },
  { en: "then", ru: "" },
  { en: "it's", ru: "" },
  { en: "don't", ru: "" },
  { en: "it has", ru: "" },
  { en: "have", ru: "" },
  { en: "better", ru: "" },
  { en: "more", ru: "" },
  { en: "less", ru: "" },
  { en: "no", ru: "" },
  { en: "Response A", ru: "" },
  { en: "Response B", ru: "" },
];
